name: 'dida'
hparams:
  hidden_size: 64
  n_layers: 2
  heads: 4
  norm: 1
  lin_bias: false
  dropout: 0.
  skip: 0
  use_RTE: true
  fmask: true
  only_causal: true
regs:
  int_times: 10
  y1: 0.01 # SS-MMD Loss
