name: 'unkrig'
hparams:
  hidden_size: 64
  exog_size: 0
  enc_layers: 1
  gcn_layers: 2
  dropout: 0.4
  intervention_steps: 2
  mmd_sample_ratio: 0.4
regs:
  y1: 0.2 # SS-MMD Loss
  y2: 1 # IRM Loss
  y3: 0.8 # Similarity Loss

# technique:
#   inductive: True
#   randomise: False
#   start_active: 10
#   storage_size: 50
#   distance_metric: 'kl'
#   graph_feature: 'n_degree'
#   # individual_reg: 0.1