name: 'unkrigv5woCRL'
hparams:
  hidden_size: 64
  exog_size: 0
  gcn_layers: 1
  psd_layers: 1
  dropout: 0.4
  intervention_steps: 5
  mmd_sample_ratio: 0.8
  att_window: 3
  k: 3
regs:
  dloss: 'cmd'
  y1: 1 # SS-MMD Loss
  y2: 0 # IRM Loss
