name: 'unkrigv3'
hparams:
  hidden_size: 64
  exog_size: 0
  enc_layers: 1
  gcn_layers: 1
  psd_layers: 1
  dropout: 0.4
  intervention_steps: 2
  mmd_sample_ratio: 0.2
  k: 3
regs:
  dloss: 'mmd'
  y1: 0.8 # SS-MMD Loss
  y2: 1 # IRM Loss
