#### Dataset params ###########################################################
name: air
masked_sensors: [0, 4, 5, 6, 10, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 26, 29, 31, 32]
splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  threshold: 0.1
  include_self: False