#### Dataset params ###########################################################
name: air_invercargill1
masked_sensors: [36, 39, 38, 21, 12, 22, 27,  0,  4, 37, 25, 40, 14, 10, 2, 32,  5, 17,  7, 15]
test_month: [8]
agg_func: 'mean'
location: 'Invercargill1'
t_range: ['2023-07-01', '2023-09-01']
splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  threshold: 1e-4
  include_self: False