#### Dataset params ###########################################################
name: air_invercargill2
masked_sensors: [5]
test_month: [6]
agg_func: 'mean'
location: 'Invercargill2'
t_range: ['2023-08-01', '2023-10-01']
splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  threshold: 1e-4
  include_self: False