#### Dataset params ###########################################################
name: aqi

# temporal shift
shift: false

# Point
mode: region
p_fault: 0.
p_noise: 0.25

# Block
# p_fault: 0.0015
# p_noise : 0.05
splitting:
  val_len: 0.1
  test_len: 0.2
  gran: month
  test_times: [1, 2, 12]
connectivity:
  method: distance
  threshold: 0.1
  include_self: False