#### Dataset params ###########################################################
name: electricity
# Point
mode: 'region'
p_fault: 0.
p_noise: 0.25

# spatial shift
spatial_shift: false
order: 0
node_features: c_centrality

splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: precomputed
  threshold: 0.
  include_self: False