#### Dataset params ###########################################################
name: pem04

# spatial shift
spatial_shift: false
order: 0
node_features: c_centrality

# Point
mode: 'region'
p_fault: 0.
p_noise: 0.25

# Block
# p_fault: 0.0015
# p_noise : 0.05
splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  threshold: 0.1
  include_self: False