#### Dataset params ###########################################################
name: sd

# temporal shift
shift: false

# spatial shift
spatial_shift: false
order: 0
node_features: c_centrality

# Point
mode: region
p_fault: 0.
p_noise: 0.25

splitting:
  val_len: 0.1
  test_len: 0.2
  gran: year
  test_times: [2020]
connectivity:
  method: precomputed
  threshold: 0.1
  include_self: False