name: geode
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blosc2==3.6.1
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.1.2
      - debugpy==1.8.15
      - decorator==4.4.2
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - grpcio==1.74.0
      - hydra-core==1.3.2
      - idna==3.10
      - ipykernel==6.30.0
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.8
      - lightning-utilities==0.15.0
      - llvmlite==0.44.0
      - markdown==3.8.2
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - ndindex==1.10.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.61.2
      - numexpr==2.11.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - pot==0.9.5
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyg-lib==0.3.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - requests==2.32.4
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.13.3
      - tables==3.10.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.1.0
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-geometric-temporal==0.56.2
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spatiotemporal==0.9.5
      - torch-spline-conv==1.2.2
      - torchmetrics==1.8.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yarl==1.20.1
      - --find-links https://data.pyg.org/whl/torch-2.1.0+cu121.html