# python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=aqism' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=aqism' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=aqism' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=aqism' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=aqism' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# sleep 60
python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=metrla' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=metrla' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=metrla' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=metrla' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=metrla' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'model.regs.y1=0.5' --config-name=default-unkrigv5
sleep 60
# python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=aqi' 'model.hparams.k=1' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=aqi' 'model.hparams.k=1' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=aqi' 'model.hparams.k=1' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=aqi' 'model.hparams.k=1' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=aqi' 'model.hparams.k=1' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
# sleep 60
python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-al' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-al' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-al' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-al' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-al' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
sleep 60
python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-md' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-md' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-md' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-md' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=nrel-md' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y1=0.5' --config-name=default-unkrigv5
sleep 60
python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=pem04' 'model.hparams.k=2' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=pem04' 'model.hparams.k=2' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=pem04' 'model.hparams.k=2' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=pem04' 'model.hparams.k=2' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=pem04' 'model.hparams.k=2' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
sleep 60
python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=pem07' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=pem07' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=pem07' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=pem07' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=pem07' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y1=0.5' --config-name=default-unkrigv5
sleep 60
python3 Imputation/mult_experiments.py '+seed=15900376' 'device=[2]' 'dataset.mode=road' 'dataset=sd' 'stride=6' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=63273150' 'device=[2]' 'dataset.mode=road' 'dataset=sd' 'stride=6' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=10799678' 'device=[2]' 'dataset.mode=road' 'dataset=sd' 'stride=6' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=72833750' 'device=[2]' 'dataset.mode=road' 'dataset=sd' 'stride=6' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5
python3 Imputation/mult_experiments.py '+seed=53728009' 'device=[2]' 'dataset.mode=road' 'dataset=sd' 'stride=6' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'batch_size=32' 'model.regs.y1=0.5' --config-name=default-unkrigv5 