# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=aqism' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y2=0.5' --config-name=default
# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=aqi' 'model.hparams.k=1' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'batch_size=16' 'optimizer.hparams.lr=0.001' 'model.regs.y2=0.5' --config-name=default
# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=metrla' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'model.regs.y2=0.5' --config-name=default
# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=nrel-al' 'stride=12'  'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=16' 'model.regs.y2=0.5' --config-name=default
# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=nrel-md' 'stride=12'  'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=16' 'model.regs.y2=0.5' --config-name=default
# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=pem04' 'model.hparams.k=2' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y2=0.5' --config-name=default
# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=pem07' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y2=0.5' --config-name=default
# python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=sd' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'batch_size=16' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=aqism' 'model.hparams.k=2' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=aqi' 'model.hparams.k=1' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'batch_size=16' 'optimizer.hparams.lr=0.001' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=metrla' 'model.hparams.k=2' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=nrel-al' 'stride=12'  'model.hparams.k=2' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=16' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=nrel-md' 'stride=12'  'model.hparams.k=2' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=16' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=pem04' 'model.hparams.k=2' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=pem07' 'stride=12' 'model.hparams.k=3' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=sd' 'stride=12' 'model.hparams.k=3' 'dataset.spatial_shift=true' 'model.hparams.psd_layers=3' 'model.hparams.gcn_layers=2' 'batch_size=16' 'model.regs.y2=0.5' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=aqism' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=metrla' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=3' 'optimizer.hparams.lr=0.00001' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=aqi' 'batch_size=16' 'model.hparams.k=2' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=2' 'optimizer.hparams.lr=0.0001' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=nrel-al' 'batch_size=16' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'batch_size=32' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=nrel-md' 'batch_size=16' 'model.hparams.k=2' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=1' 'optimizer.hparams.lr=0.0001' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=pem04' 'model.hparams.k=5' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=4' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=pem07' 'stride=12' 'model.hparams.k=6' 'model.hparams.psd_layers=2' 'model.hparams.gcn_layers=4' 'optimizer.hparams.lr=0.00001' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default
python3 model/mult_experiments.py '+seed=15900376' 'device=[2]' 'epochs=1' 'dataset=sd' 'batch_size=16' 'stride=12' 'model.hparams.k=3' 'model.hparams.psd_layers=1' 'model.hparams.gcn_layers=4' 'batch_size=32' 'optimizer.hparams.lr=0.00001' 'dataset.p_noise=0.50' 'eval_setting=test_wise' --config-name=default