name: geodeCrossV7
hparams:
  hidden_size: 64
  gcn_layers: 1
  psd_layers: 1
  intervention_steps: 5
  cmd_sample_ratio: 1
  tra_sample_ratio: 0.75
  att_window: 1
  nbcd_layers: 1
  k: 3
regs:
  y1: 0.3 # IRM Loss
  y2: 1.0 # Contastive Loss
  temp: 0.25 # InfoNCE temp
