#### Dataset params ###########################################################
name: aqi

# spatial shift
spatial_shift: false
order: 0
node_features: c_centrality

# Point
mode: road
p_fault: 0.
p_noise: 0.25

splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  threshold: 0.01
  include_self: False