# @package _global_

#### Model params #############################################################
model:
  name: grugcn
  hparams:
    hidden_size: 512
    enc_layers: 1
    gcn_layers: 2
    norm: mean

#### Config overrides #########################################################
batch_size: 256

optimizer:
  hparams:
    lr: 0.003

lr_scheduler:
  name: MultiStepLR
  hparams:
    gamma: 0.25
    milestones: [ 25, 50, 100 ]