#### Dataset params ###########################################################
name: air_auckland
test_month: [5]
agg_func: 'mean'
splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  threshold: 1e-4
  include_self: False