#### Dataset params ###########################################################
name: air_smaller
masked_sensors: [5]
splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  include_self: False