defaults:
  - _self_
  - logger: null
  - dataset: air_auckland
  - model: dcrnn

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${model.name}/${dataset.name}/${hydra.job.num}

seed: 42  # automatically set everywhere the seed
tags:
  - ${model.name}
  - ${dataset.name}

workers: 0
num_threads: 1  # limit the number of pytorch threads spawn

logger: tensorboard

#### Windowing params #########################################################
window: 12
horizon: 12
stride: 12

#### Training params ##########################################################
epochs: 500
patience: 50
batch_size: 64
grad_clip_val: 5
scale_target: False
device: [3]

optimizer:
  name: Adam
  hparams:
    lr: 0.01
    weight_decay: 0.0001

lr_scheduler: null