defaults:
  - _self_
  - logger: null
  - dataset: air_auckland
  - model: birnni

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${model.name}/${dataset.name}/${hydra.job.num}

seed: 42  # automatically set everywhere the seed
tags:
  - ${model.name}
  - ${dataset.name}

workers: 0
num_threads: 1  # limit the number of pytorch threads spawn

logger: tensorboard

#### Windowing params #########################################################
window: 12
stride: 12

#### Training params ##########################################################
epochs: 300
patience: 50
batch_size: 128
grad_clip_val: 5
scale_target: False
whiten_prob: 0.05
prediction_loss_weight: 1
impute_only_missing: False
warm_up_steps: 0
device: [2]

scaled_target: True
detrend: False
scale: True
scaling_axis: 'global'  # ['channels', 'global']


optimizer:
  name: Adam
  hparams:
    lr: 0.01
    weight_decay: 0

lr_scheduler: null